## 📦 Import Libraries

In [13]:
import numpy as np
import pandas as pd

## 📂 Load Dataset

In [14]:
df = pd.read_csv(r"E:\Work\Power bi\رواد مصر\HR Analysis Project\Dataset\HRDataset_v14.csv")

In [15]:
pd.set_option('display.max_columns', None)
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,PositionID,Position,State,Zip,DOB,Sex,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,0,19,Production Technician I,MA,1960,07/10/83,M,Single,US Citizen,No,White,7/5/2011,NaN,N/A-StillEmployed,Active,Production,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,1,27,Sr. DBA,MA,2148,05/05/75,M,Married,US Citizen,No,White,3/30/2015,6/16/2016,career change,Voluntarily Terminated,IT/IS,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,1,20,Production Technician II,MA,1810,09/19/88,F,Married,US Citizen,No,White,7/5/2011,9/24/2012,hours,Voluntarily Terminated,Production,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,0,19,Production Technician I,MA,1886,09/27/88,F,Married,US Citizen,No,White,1/7/2008,NaN,N/A-StillEmployed,Active,Production,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,1,19,Production Technician I,MA,2169,09/08/89,F,Divorced,US Citizen,No,White,7/11/2011,9/6/2016,return to school,Voluntarily Terminated,Production,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,0,20,Production Technician II,MA,1810,05/11/85,M,Single,US Citizen,No,White,7/7/2014,NaN,N/A-StillEmployed,Active,Production,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,1,19,Production Technician I,MA,2458,05/04/82,F,Single,US Citizen,No,Asian,9/2/2008,9/29/2015,Another position,Voluntarily Terminated,Production,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,0,6,CIO,MA,2067,08/30/79,F,Single,US Citizen,No,White,4/10/2010,NaN,N/A-StillEmployed,Active,IT/IS,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,0,9,Data Analyst,MA,2148,02/24/79,F,Single,US Citizen,No,White,3/30/2015,NaN,N/A-StillEmployed,Active,IT/IS,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,0,19,Production Technician I,MA,1730,08/17/78,F,Widowed,US Citizen,No,Asian,9/29/2014,NaN,N/A-StillEmployed,Active,Production,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

## 🔍 Initial Data Exploration
Quick look at data types, null values, and column names.

In [16]:
df.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                             0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [17]:
df.dtypes

Employee_Name                  object
EmpID                           int64
MarriedID                       int64
MaritalStatusID                 int64
GenderID                        int64
EmpStatusID                     int64
DeptID                          int64
PerfScoreID                     int64
FromDiversityJobFairID          int64
Salary                          int64
Termd                           int64
PositionID                      int64
Position                       object
State                          object
Zip                             int64
DOB                            object
Sex                            object
MaritalDesc                    object
CitizenDesc                    object
HispanicLatino                 object
RaceDesc                       object
DateofHire                     object
DateofTermination              object
TermReason                     object
EmploymentStatus               object
Department                     object
ManagerName                    object
ManagerID                     float64
RecruitmentSource              object
PerformanceScore               object
EngagementSurvey              float64
EmpSatisfaction                 int64
SpecialProjectsCount            int64
LastPerformanceReview_Date     object
DaysLateLast30                  int64
Absences                        int64
dtype: object

In [18]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='object')

## 🔧 Fix Data Types
Convert date columns from `object` to `datetime`, and fix `ManagerID` to integer.

In [19]:
# Fix DOB - handle 2-digit years correctly (e.g. '75' → 1975 not 2075)
df['DOB'] = pd.to_datetime(df['DOB'], format='%m/%d/%y')
df['DOB'] = df['DOB'].apply(lambda x: x.replace(year=x.year - 100) if x.year > 2005 else x)

# Convert remaining date columns
df['DateofHire'] = pd.to_datetime(df['DateofHire'])
df['LastPerformanceReview_Date'] = pd.to_datetime(df['LastPerformanceReview_Date'])

In [20]:
df['ManagerID'] = df['ManagerID'].astype('Int64')

In [21]:
df.dtypes

Employee_Name                         object
EmpID                                  int64
MarriedID                              int64
MaritalStatusID                        int64
GenderID                               int64
EmpStatusID                            int64
DeptID                                 int64
PerfScoreID                            int64
FromDiversityJobFairID                 int64
Salary                                 int64
Termd                                  int64
PositionID                             int64
Position                              object
State                                 object
Zip                                    int64
DOB                           datetime64[ns]
Sex                                   object
MaritalDesc                           object
CitizenDesc                           object
HispanicLatino                        object
RaceDesc                              object
DateofHire                    datetime64[ns]
DateofTermination                     object
TermReason                            object
EmploymentStatus                      object
Department                            object
ManagerName                           object
ManagerID                              Int64
RecruitmentSource                     object
PerformanceScore                      object
EngagementSurvey                     float64
EmpSatisfaction                        int64
SpecialProjectsCount                   int64
LastPerformanceReview_Date    datetime64[ns]
DaysLateLast30                         int64
Absences                               int64
dtype: object

## 🧹 Handle Termination Columns
- Replace `N/A-StillEmployed` in `TermReason` with a cleaner label
- Verify logic: `Termd=0` should have no termination date, `Termd=1` should have one
- Fill missing `DateofTermination` for active employees with the last known date in the dataset

In [22]:
df["TermReason"] = df["TermReason"].replace("N/A-StillEmployed", "Still Employed")

In [23]:
df[["Employee_Name", "DateofTermination", "Termd", "TermReason"]]

                Employee_Name DateofTermination  Termd        TermReason
0         Adinolfi, Wilson  K               NaN      0    Still Employed
1    Ait Sidi, Karthikeyan            6/16/2016      1     career change
2           Akinkuolie, Sarah         9/24/2012      1             hours
3                Alagbe,Trina               NaN      0    Still Employed
4            Anderson, Carol           9/6/2016      1  return to school
..                        ...               ...    ...               ...
306            Woodson, Jason               NaN      0    Still Employed
307        Ybarra, Catherine          9/29/2015      1  Another position
308          Zamora, Jennifer               NaN      0    Still Employed
309               Zhou, Julia               NaN      0    Still Employed
310             Zima, Colleen               NaN      0    Still Employed

[311 rows x 4 columns]

In [24]:
# Validate: all active employees (Termd=0) should have no termination date
(df[df["Termd"] == 0]["DateofTermination"].isna()).all()

np.True_

In [25]:
# Validate: no terminated employees (Termd=1) should have a missing termination date
(df[df["Termd"] == 1]["DateofTermination"].isna()).any()

np.False_

In [26]:
# Convert DateofTermination to datetime first
df["DateofTermination"] = pd.to_datetime(df["DateofTermination"])

In [27]:
# Check last known date in dataset to use as fill value for active employees
print(df["LastPerformanceReview_Date"].max())

2019-02-28 00:00:00

In [28]:
# Fill missing DateofTermination for active employees with dataset's last known date
df["DateofTermination"] = df["DateofTermination"].fillna(pd.Timestamp("2019-02-28"))

## 👤 Fix Missing ManagerID
Identify employees with a missing `ManagerID` and fill it manually based on known data.

In [29]:
df[df["ManagerID"].isna()][["ManagerName", "ManagerID"]]

        ManagerName  ManagerID
19   Webster Butler       <NA>
30   Webster Butler       <NA>
44   Webster Butler       <NA>
88   Webster Butler       <NA>
135  Webster Butler       <NA>
177  Webster Butler       <NA>
232  Webster Butler       <NA>
251  Webster Butler       <NA>

In [30]:
df["ManagerName"].value_counts()

ManagerName
Michael Albert        22
Kissy Sullivan        22
Elijiah Gray          22
Kelley Spirea         22
Brannon Miller        22
Ketsia Liebig         21
David Stanley         21
Amy Dunn              21
Webster Butler        21
Janet King            19
Simon Roup            17
Peter Monroe          14
John Smith            14
Lynn Daneault         13
Alex Sweetwater        9
Brian Champaigne       8
Brandon R. LeBlanc     7
Jennifer Zamora        7
Eric Dougall           4
Debra Houlihan         3
Board of Directors     2
Name: count, dtype: int64

In [31]:
# Webster Butler is not in the dataset as an employee — assign ID manually
df.loc[df["ManagerName"] == "Webster Butler", "ManagerID"] = 39

## 🧼 Clean Categorical Columns
Remove whitespace and fix inconsistent casing in text columns.

In [32]:
df['Department'] = df['Department'].str.strip()
df['Position'] = df['Position'].str.strip()
df['Sex'] = df['Sex'].str.strip()
df['HispanicLatino'] = df['HispanicLatino'].str.strip().str.title()
df['TermReason'] = df['TermReason'].str.strip().str.title()

In [33]:
# Verify unique values for key categorical columns
cols = ["Position", "MaritalDesc", "EmploymentStatus", "Department", "RecruitmentSource", "PerformanceScore"]
for col in cols:
    print(f"\n--- {col} ---")
    print(df[col].unique())

--- Position ---
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'CIO']

--- MaritalDesc ---
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']

--- EmploymentStatus ---
['Active' 'Voluntarily Terminated' 'Terminated for Cause']

--- Department ---
['Production' 'IT/IS' 'Software Engineering' 'Admin Offices' 'Sales'
 'Executive Office']

--- RecruitmentSource ---
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']

--- PerformanceScore ---
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']

## 🔁 Check for Duplicates

In [34]:
df.duplicated().sum()

np.int64(0)

## ✅ Final Null Check
Confirm all missing values have been handled.

In [35]:
df.isnull().sum().sum()

np.int64(0)

In [36]:
df.isnull().sum()

Employee_Name                 0
EmpID                         0
MarriedID                     0
MaritalStatusID               0
GenderID                      0
EmpStatusID                   0
DeptID                        0
PerfScoreID                   0
FromDiversityJobFairID        0
Salary                        0
Termd                         0
PositionID                    0
Position                      0
State                         0
Zip                           0
DOB                           0
Sex                           0
MaritalDesc                   0
CitizenDesc                   0
HispanicLatino                0
RaceDesc                      0
DateofHire                    0
DateofTermination             0
TermReason                    0
EmploymentStatus              0
Department                    0
ManagerName                   0
ManagerID                     0
RecruitmentSource             0
PerformanceScore              0
EngagementSurvey              0
EmpSatisfaction               0
SpecialProjectsCount          0
LastPerformanceReview_Date    0
DaysLateLast30                0
Absences                      0
dtype: int64

## ⚙️ Feature Engineering
Create new columns to enrich the dataset for analysis:
- `Age` — employee age based on DOB vs dataset reference date (2019-02-28)
- `AgeGroup` — categorized age buckets
- `TenureYears` — years of service (rounded to 2 decimal places)
- `IsActive` — readable employment status
- `DaysSinceReview` — days since last performance review

In [37]:
# Age as of dataset reference date (2019-02-28)
df['Age'] = (pd.Timestamp('2019-02-28') - df['DOB']).dt.days // 365

In [38]:
# Age group buckets
df['AgeGroup'] = df['Age'].apply(lambda x:
    'Under 30' if x < 30 else
    '30s' if x < 40 else
    '40s' if x < 50 else
    '50s' if x < 60 else
    '60+'
)

In [39]:
# Years of service
df['TenureYears'] = round((df['DateofTermination'] - df['DateofHire']).dt.days / 365, 2)

In [40]:
# Readable employment status
df['IsActive'] = df['Termd'].apply(lambda x: 'Active' if x == 0 else 'Terminated')

In [41]:
# Days since last performance review
df['DaysSinceReview'] = (pd.Timestamp('2019-02-28') - df['LastPerformanceReview_Date']).dt.days

# ──────────────────────────────────────────────
## 🎯 Final Dataset Preview
### ✅ Data is clean and ready for analysis.
# ──────────────────────────────────────────────

In [42]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,PositionID,Position,State,Zip,DOB,Sex,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Age,AgeGroup,TenureYears,IsActive,DaysSinceReview
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,0,19,Production Technician I,MA,1960,1983-07-10,M,Single,US Citizen,No,White,2011-07-05,2019-02-28,Still Employed,Active,Production,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1,35,30s,7.66,Active,42
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,1,27,Sr. DBA,MA,2148,1975-05-05,M,Married,US Citizen,No,White,2015-03-30,2016-06-16,Career Change,Voluntarily Terminated,IT/IS,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17,43,40s,1.22,Terminated,1100
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,1,20,Production Technician II,MA,1810,1988-09-19,F,Married,US Citizen,No,White,2011-07-05,2012-09-24,Hours,Voluntarily Terminated,Production,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3,30,30s,1.22,Terminated,2480
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,0,19,Production Technician I,MA,1886,1988-09-27,F,Married,US Citizen,No,White,2008-01-07,2019-02-28,Still Employed,Active,Production,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15,30,30s,11.15,Active,56
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,1,19,Production Technician I,MA,2169,1989-09-08,F,Divorced,US Citizen,No,White,2011-07-11,2016-09-06,Return To School,Voluntarily Terminated,Production,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2,29,Under 30,5.16,Terminated,1123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,0,20,Production Technician II,MA,1810,1985-05-11,M,Single,US Citizen,No,White,2014-07-07,2019-02-28,Still Employed,Active,Production,Kissy Sullivan,20,LinkedIn,Fully Meets,4.07,4,0,2019-02-28,0,13,33,30s,4.65,Active,0
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,1,19,Production Technician I,MA,2458,1982-05-04,F,Single,US Citizen,No,Asian,2008-09-02,2015-09-29,Another Position,Voluntarily Terminated,Production,Brannon Miller,12,Google Search,PIP,3.20,2,0,2015-09-02,5,4,36,30s,7.08,Terminated,1275
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,0,6,CIO,MA,2067,1979-08-30,F,Single,US Citizen,No,White,2010-04-10,2019-02-28,Still Employed,Active,IT/IS,Janet King,2,Employee Referral,Exceeds,4.60,5,6,2019-02-21,0,16,39,30s,8.89,Active,7
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,0,9,Data Analyst,MA,2148,1979-02-24,F,Single,US Citizen,No,White,2015-03-30,2019-02-28,Still Employed,Active,IT/IS,Simon Roup,4,Employee Referral,Fully Meets,5.00,3,5,2019-02-01,0,11,40,40s,3.92,Active,27
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,0,19,Production Technician I,MA,1730,1978-08-17,F,Widowed,US Citizen,No,Asian,2014-09-29,2019-02-28,Still Employed,Active,Production,David Stanley,14,LinkedIn,Fully Meets,4.50,5,0,2019-01-30,0,2,40,40s,4.42,Active,29

---
## 🗄️ Export to SQL Database
Connect to SQL Server using SQLAlchemy and export the cleaned dataset.

In [43]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
from sqlalchemy import create_engine

server = r'DESKTOP-J0HPDNG\SQLEXPRESS'
database = 'HR_DataBase'
driver = 'ODBC Driver 17 for SQL Server'

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver.replace(' ', '+')}&trusted_connection=yes&TrustServerCertificate=yes"
)

### 🗓️ Fix Date Format Before Export
Remove the time component `00:00:00.000` so dates appear clean in SQL Server.

In [45]:
# Re-convert to datetime to ensure .dt accessor works
df['DOB'] = pd.to_datetime(df['DOB'])
df['DateofHire'] = pd.to_datetime(df['DateofHire'])
df['DateofTermination'] = pd.to_datetime(df['DateofTermination'])
df['LastPerformanceReview_Date'] = pd.to_datetime(df['LastPerformanceReview_Date'])

# Strip time component — keeps date only (e.g. 1983-07-10)
df['DOB'] = df['DOB'].dt.date
df['DateofHire'] = df['DateofHire'].dt.date
df['DateofTermination'] = df['DateofTermination'].dt.date
df['LastPerformanceReview_Date'] = df['LastPerformanceReview_Date'].dt.date

In [46]:
table_name = "HR_Table"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print("✅ Data uploaded successfully!")

C:\Users\aly_2005\AppData\Local\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

✅ Data uploaded successfully!

In [47]:
pd.read_sql("SELECT TOP 5 * FROM HR_Table", engine)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,PositionID,Position,State,Zip,DOB,Sex,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Age,AgeGroup,TenureYears,IsActive,DaysSinceReview
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,0,19,Production Technician I,MA,1960,1983-07-10,M,Single,US Citizen,No,White,2011-07-05,2019-02-28,Still Employed,Active,Production,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1,35,30s,7.66,Active,42
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,1,27,Sr. DBA,MA,2148,1975-05-05,M,Married,US Citizen,No,White,2015-03-30,2016-06-16,Career Change,Voluntarily Terminated,IT/IS,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17,43,40s,1.22,Terminated,1100
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,1,20,Production Technician II,MA,1810,1988-09-19,F,Married,US Citizen,No,White,2011-07-05,2012-09-24,Hours,Voluntarily Terminated,Production,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3,30,30s,1.22,Terminated,2480
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,0,19,Production Technician I,MA,1886,1988-09-27,F,Married,US Citizen,No,White,2008-01-07,2019-02-28,Still Employed,Active,Production,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15,30,30s,11.15,Active,56
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,1,19,Production Technician I,MA,2169,1989-09-08,F,Divorced,US Citizen,No,White,2011-07-11,2016-09-06,Return To School,Voluntarily Terminated,Production,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2,29,Under 30,5.16,Terminated,1123